### PR TITLE
Cache separate canonical URLs for @use and @import

### LINKED ISSUE #899: Incorrect behavior when a stylesheet in a load path is loaded by both `@use` and `@import`
For example:
```scss
// app.scss
@use "library";
@import "library";

// load-path/_library.scss
a { b: regular; }

// load-path/_library.import.scss
a { b: import-only; }
```
should output the regular styles followed by the import-only styles (and it does so if the rules' URLs are relative), but instead it outputs the regular styles twice.

I believe this is due to `ImportCache` using the same canonicalization cache for both `@import` and `@use` rules (I actually ran into this with the migrator initially).

### PR DESCRIPTION
**Pull request by jathak**
Fixes #899.

The cache for canonical URLs is now keyed on *both* the rule URL and
whether that URL was canonicalized for an `@import` rule.

### CODE REVIEW

File: lib/src/async_import_cache.dart [hunk 1]
```diff
@@ -132,8 +139,14 @@ class AsyncImportCache {
 
   /// Calls [importer.canonicalize] and prints a deprecation warning if it
   /// returns a relative URL.
-  Future<Uri> _canonicalize(AsyncImporter importer, Uri url) async {
-    var result = await importer.canonicalize(url);
+  Future<Uri> _canonicalize(
+      AsyncImporter importer, Uri url, bool forImport) async {
+    Uri result;
+    if (forImport) {
```
Comment (nex3) [inline lib/src/async_import_cache.dart]: Style nit: I'd use `? :` here to save a few lines of boilerplate.

File: lib/src/importer/utils.dart [hunk 2]
```diff
@@ -6,43 +6,42 @@ import 'package:path/path.dart' as p;
...
-    _inUseRule = wasInUseRule;
+    _inImportRule = wasInImportRule;
   }
 }
 
 /// Resolves an imported path using the same logic as the filesystem importer.
 ///
-/// This tries to fill in extensions and partial prefixes and check if a directory default. If no file can be
-/// found, it returns `null`.
+/// This tries to fill in extensions and partial prefixes and check if a
```
Comment (nex3) [inline lib/src/importer/utils.dart]:
```suggestion
/// This tries to fill in extensions and partial prefixes and check for a
```

File: lib/src/stylesheet_graph.dart [hunk 3]
```diff
@@ -92,14 +93,17 @@ class StylesheetGraph {
 
   /// Returns a map from non-canonicalized imported URLs in [stylesheet], which
```
Comment (nex3) [inline lib/src/stylesheet_graph.dart]: Document the new map value.

File: lib/src/stylesheet_graph.dart [hunk 4]
```diff
@@ -237,8 +242,9 @@ class StylesheetNode {
   /// stylesheets those imports refer to.
   ///
   /// This may have `null` values, which indicate failed imports.
-  Map<Uri, StylesheetNode> get upstream => UnmodifiableMapView(_upstream);
-  Map<Uri, StylesheetNode> _upstream;
+  Map<Tuple2<Uri, bool>, StylesheetNode> get upstream =>
```
Comment (nex3) [inline lib/src/stylesheet_graph.dart]: It's plausible that we'll want to expose this class publicly relatively soon, and I really don't want to have to break this API once we remove imports. WDYT about making `upstream` refer only to `@use` and `@import`, and have a separate `upstreamImports` field that only contains imports?

Comment (jathak) [reply lib/src/stylesheet_graph.dart]: Yeah, that makes sense. I went back and forth on whether to key on a tuple or just have two maps while I was writing this. Would it make sense to do the same in `ImportCache` for consistency?

Comment (nex3) [reply lib/src/stylesheet_graph.dart]: Since `ImportCache`'s map isn't part of its public API, I think it's fine to have it stay as tuple-keyed.

File: lib/src/executable/watch.dart [hunk 5]
```diff
@@ -298,15 +299,22 @@ class _Watcher {
...
+            // If the call to canonicalize failed, do nothing. We'll surface
+            // the error more nicely when we try to recompile the file.
           }
-          importChanged = newCanonicalUrl != node.upstream[url]?.canonicalUrl;
+          importChanged = newCanonicalUrl != node?.canonicalUrl;
         }
       }
+
+      node.upstream.forEach(recanonicalize);
+      forImport = true;
```
Comment (nex3) [inline lib/src/executable/watch.dart]: Rather than using this as implicit state, I'd just pass it to `recanonicalize()`. It does mean you'll have to expand those `forEach()` calls, but I think the clarity of flow is worth it.

File: lib/src/stylesheet_graph.dart [hunk 6]
```diff
@@ -39,7 +40,10 @@ class StylesheetGraph {
     DateTime transitiveModificationTime(StylesheetNode node) {
       return _transitiveModificationTimes.putIfAbsent(node.canonicalUrl, () {
         var latest = node.importer.modificationTime(node.canonicalUrl);
-        for (var upstream in node.upstream.values) {
+        for (var upstream in {
+          ...node.upstream.values,
+          ...node.upstreamImports.values
```
Comment (nex3) [inline lib/src/stylesheet_graph.dart]: I'd use [`Iterable.followedBy()`](https://api.dartlang.org/stable/2.7.0/dart-core/Iterable/followedBy.html) here to avoid copying everything into a set eagerly. There's a possibility we'll visit a file twice, but that seems unlikely and it won't affect the result.

Similar below.

File: lib/src/stylesheet_graph.dart (hunk 3 above)
Comment (nex3) [reply lib/src/stylesheet_graph.dart]: It looks like this doc comment still needs to be updated.

File: lib/src/visitor/find_dependencies.dart [hunk 7]
```diff
@@ -2,21 +2,28 @@
...
-    _FindImportsVisitor().run(stylesheet);
-
-/// A visitor that traverses a stylesheet and records all the [DynamicImport]s
-/// it contains.
-class _FindImportsVisitor extends RecursiveStatementVisitor<void> {
+/// Returns two lists of dependencies for [stylesheet].
+///
+/// The first is a list of URLs from all `@use` and `@forward` rules in
+/// [stylesheet]. The second is a list of all imports in [stylesheet].
+Tuple2<List<Uri>, List<DynamicImport>> findDependencies(
```
Comment (nex3) [inline lib/src/visitor/find_dependencies.dart]: Why aren't imports represented as `Uri`s as well?

File: lib/src/stylesheet_graph.dart [hunk 8]
```diff
@@ -233,29 +241,45 @@ class StylesheetNode {
   /// The canonical URL of [stylesheet].
   final Uri canonicalUrl;
 
-  /// A map from non-canonicalized import URLs in [stylesheet] to the
-  /// stylesheets those imports refer to.
+  /// A map from non-canonicalized `@use` and `@forward` URLs in [stylesheet] to
+  /// the stylesheets those rules refer to.
   ///
   /// This may have `null` values, which indicate failed imports.
```
Comment (nex3) [inline lib/src/stylesheet_graph.dart]:
```suggestion
  /// This may have `null` values, which indicate failed loads.
```

**Comment by jathak** [comment]
@nex3: Can you restart the AppVeyor build? I don't think I have permission

**Comment by nex3** [comment]
Done.

File: lib/src/executable/watch.dart [hunk 9]
```diff
@@ -288,8 +288,8 @@ class _Watcher {
     var changed = <StylesheetNode>[];
     for (var node in _graph.nodes.values) {
       var importChanged = false;
-      for (var url in node.upstream.keys) {
-        if (_name(p.url.basename(url.path)) != name) continue;
+      void recanonicalize(Uri url, StylesheetNode upstream, bool forImport) {
```
Comment (nex3) [inline lib/src/executable/watch.dart]: Nit:

```suggestion
      void recanonicalize(Uri url, StylesheetNode upstream, {@required bool forImport}) {
```

This just helps make it clearer at the callsite what the boolean means.
