### PR TITLE
Fix escaped backslash crash

### LINKED ISSUE #1855: Crash when selector ends with escaped backslash and no whitespace
`dart-sass` will crash on the following input:
 ```scss
\\{}
```

<details>
<summary>Stacktrace</summary>

```
Unexpected exception:
RangeError (end): Invalid value: Not in inclusive range 0..8: 9


dart:core                                               _StringBase.substring
package:sass/src/utils.dart 78                          trimAscii
package:sass/src/visitor/evaluate.dart 3153             _EvaluateVisitor._interpolationToValue
package:sass/src/visitor/evaluate.dart 1869             _EvaluateVisitor.visitStyleRule
package:sass/src/ast/sass/statement/style_rule.dart 30  StyleRule.accept
package:sass/src/visitor/evaluate.dart 938              _EvaluateVisitor.visitStylesheet
package:sass/src/visitor/evaluate.dart 746              _EvaluateVisitor._execute.<fn>
package:sass/src/visitor/evaluate.dart 3139             _EvaluateVisitor._withEnvironment
package:sass/src/visitor/evaluate.dart 716              _EvaluateVisitor._execute
package:sass/src/visitor/evaluate.dart 532              _EvaluateVisitor.run.<fn>
dart:async                                              runZoned
package:sass/src/evaluation_context.dart 57             withEvaluationContext
package:sass/src/visitor/evaluate.dart 525              _EvaluateVisitor.run
package:sass/src/visitor/evaluate.dart 97               evaluate
package:sass/src/compile.dart 151                       _compileStylesheet
package:sass/src/compile.dart 68                        compile
package:sass/src/executable/compile_stylesheet.dart 97  compileStylesheet
d:\a\dart-sass\dart-sass\bin\sass.dart 65               main
```

</details>

### PR DESCRIPTION
**Pull request by jathak**
Fixes #1855.

See https://github.com/sass/sass-spec/pull/1867.

### CODE REVIEW

File: lib/src/utils.dart [hunk 1]
```diff
@@ -115,7 +115,8 @@ int? _lastNonWhitespace(String string, {bool excludeEscape = false}) {
       if (excludeEscape &&
           i != 0 &&
           i != string.length &&
```
Comment (connorskees) [inline lib/src/utils.dart:117]: Can `i` ever be `string.length`?  I think this condition should actually be checking against `string.length - 1`. That said, this fix does appear to solve the crash as well

Comment (jathak) [reply lib/src/utils.dart:117]: Good point. That's actually a cleaner solution, so I'll change it to that. Thanks!

**Review by nex3 — APPROVED** [review]
