### PR TITLE
Parse silent comments in `_interpolatedDeclarationValue()`

### LINKED ISSUE #2263: Silent comments are incorrectly preserved in at-rule values
For example, the SCSS stylesheet

```scss
@foo bar // comment
```

currently produces the CSS

```css
@foo bar // comment;
```

([Playground link](https://sass-lang.com/playground/#eJwzNHRIy89XSEosUtDXV0jOz81NzSvhAgBMAQbX))

This is invalid, and an incorrect interpretation of the silent comment semantics.

### PR DESCRIPTION
**Pull request by nex3**
Closes #2263

See sass/sass-spec#2000

### CODE REVIEW

File: lib/src/parse/parser.dart [hunk 1]
```diff
@@ -133,7 +133,8 @@ class Parser {
     whitespace();
   }
 
-  /// Consumes and ignores a silent (Sass-style) comment.
+  /// Consumes and ignores a single silent (Sass-style) comment, not including
+  /// the trailing newline.
```
Comment (Goodwine) [inline lib/src/parse/parser.dart:137]: "not including the trailing newline" makes me wonder about what happens when there are consecutive lines with silent comments, but otherwise LGTM

**Review by Goodwine — APPROVED** [review]

File: lib/src/parse/parser.dart (hunk 1 above)
Comment (nex3) [reply lib/src/parse/parser.dart:137]: This function will only consume one of them, but `whitespace()` will consume them all _and_ the whitespace.

File: lib/src/parse/stylesheet.dart [hunk 2]
```diff
@@ -2854,7 +2877,22 @@ abstract class StylesheetParser extends Parser {
...
+              silentComment();
+              wroteNewline = false;
+
+            case _:
+              buffer.writeCharCode(scanner.readChar());
+              wroteNewline = false;
+          }
+
+        case $slash when silentComments && scanner.peekChar(1) == $slash:
           buffer.write(rawText(loudComment));
```
Comment (stof) [inline lib/src/parse/stylesheet.dart:2896]: should this really parse a loud comment when finding `//` ? Or is this dead code because of going through the previous case all the time ?

Comment (nex3) [reply lib/src/parse/stylesheet.dart:2896]: You're right that it's incorrect and also that it's dead code. I'll send out a PR to remove it.
