### PR TITLE
Fix the URL for the @-moz-document deprecation message

### LINKED ISSUE #1336: the link in the moz-document rule deprecation is dead
The deprecation warning for `@-moz-document` contains a link to http://bit.ly/moz-document for details.

This shortened link currently resolves to https://www.fxsitecompat.dev/en-CA/docs/2018/moz-document-support-has-been-dropped-except-for-empty-url-prefix/ which returns a 410 error with this message:

> The Firefox Site Compatibility Working Group has been dissolved. Our resources are no longer available.

### PR DESCRIPTION
**Pull request by nex3**
Closes #1336
See https://github.com/sass/sass-spec/pull/1662

### CODE REVIEW

**Review by Awjin — APPROVED** [review]

File: lib/src/parse/stylesheet.dart [hunk 1]
```diff
@@ -1338,7 +1338,7 @@ abstract class StylesheetParser extends Parser {
             "@-moz-document is deprecated and support will be removed in Dart "
             "Sass 2.0.0.\n"
             "\n"
-            "For details, see http://bit.ly/moz-document.",
+            "For details, see http://bit.ly/MozDocument.",
```
Comment (stof) [inline lib/src/parse/stylesheet.dart:1341]: should it use a https link ?
