### PR TITLE
Fix a race condition with re-used compilation isolate IDs

### LINKED ISSUE #2004: `sass --embedded` race condition in deactivating isolates
There is a race condition due to the deactivation of isolation (free up a wire id) being an async callback.

In a normal flow this is what should happen.
1. Host send compilation request id=1
2. Compiler activate isolate id=1
3. Compiler send compilation response id=1
4. Compiler deactivate isolate id=1
5. Host send compilation request id=1
6. ...

However, in the test I discovered that because the deactivation happens after sending response on a event loop rather than immediately after, there is a race condition:

1. Host send compilation request id=1
2. Compiler activate isolate id=1
3. Compiler send compilation response id=1
4. Host send compilation request id=1
6. Compiler deactivate isolate id=1
7. ???

It is completely legit for host to reuse id=1 as soon as it receives the response. However, a new request with the same id may land before the hook to deactivate isolate finishes, which causes host side lockup because it will never get a response.

### PR DESCRIPTION
**Pull request by nex3**
Closes #2004

### CODE REVIEW

File: lib/src/embedded/dispatcher.dart [hunk 1]
```diff
@@ -322,10 +322,17 @@ class Dispatcher {
     var protobufWriter = CodedBufferWriter();
     message.writeToCodedBufferWriter(protobufWriter);
 
-    var packet =
-        Uint8List(_compilationIdVarint.length + protobufWriter.lengthInBytes);
-    packet.setAll(0, _compilationIdVarint);
-    protobufWriter.writeTo(packet, _compilationIdVarint.length);
+    // Add one additional byte to the beginning to indicate whether or not the
```
Comment (Goodwine) [inline lib/src/embedded/dispatcher.dart:325]: It feels error-prone to push a byte into the bytearray as a completion signal for the Isolate because then the Isolate has to remember about it and remove it before sending it to the host.

Would it make sense to wrap the bytearray with another object like a custom class or a tuple to make this signal more obvious? This would require changing the `IsolateDispatcher`'s input channel to `IsolateChannel<MyWrapper>`, but the output channel would remain the same 🤔

Comment (ntkme) [reply lib/src/embedded/dispatcher.dart:325]: Dart 3 Record would be a good fit for this. E.g. `IsolateChannel<(int, Uint8List)>`

Comment (nex3) [reply lib/src/embedded/dispatcher.dart:325]: I considered a record-based approach, but I decided against it for a couple reasons. First, I don't like the asymmetry between sending and receiving, especially given that the `StreamChannel` API requires symmetrical types. Passing an `int` that doubles as the compilation ID is a clever way around that, but ultimately moving the compilation ID out of the initial message doesn't really buy us anything—we've already got a pretty good way of providing the ID to the dispatcher isolate that doesn't require it to handle cases where it unexpectedly changes over time.

There's also the question of efficiency. I haven't measured, but my assumption is that (even as a value type) instantiating and passing records is going to be somewhat more overhead than expanding the binary buffer that already exists.

Ultimately, I'm not too worried about requiring the isolate dispatcher to narrow the buffer. Two classes that have a tightly coupled protocol is a relatively common pattern in message-passing scenarios like this.

File: lib/src/embedded/isolate_dispatcher.dart [hunk 2]
```diff
@@ -156,19 +156,28 @@ class IsolateDispatcher {
     var receivePort = ReceivePort();
     isolate.sink.add((receivePort.sendPort, compilationId));
 
-    var channel = IsolateChannel<Uint8List?>.connectReceive(receivePort)
-        .transform(const ExplicitCloseTransformer());
-    channel.stream.listen(_channel.sink.add,
+    var channel = IsolateChannel<Uint8List>.connectReceive(receivePort);
+    channel.stream.listen(
+        (message) {
+          _channel.sink.add(Uint8List.sublistView(message, 1));
```
Comment (Goodwine) [inline lib/src/embedded/isolate_dispatcher.dart:162]: If we're keeping the first byte as a special thing between the isolate and the main thread, then I think it would be helpful to add a comment immediately before this line about why we're sending a slice of the bytearray.

File: lib/src/embedded/dispatcher.dart (hunk 1 above)
Comment (Goodwine) [reply lib/src/embedded/dispatcher.dart:325]: I agree with the asymmetry concern, and with being OK with the isolate being tightly coupled (my experience working with isolates is pretty limited, but that sounds about right).

I wouldn't think the overhead would be that big, but I also didn't think appending values to a `List<T>` was expensive, and it was. 😝 

While I still think the pattern can be error prone, we do have tests which I think would catch a case where we forget to trim off the first byte.. I guess this is fine

**Review by Goodwine — APPROVED** [review]

File: lib/src/embedded/isolate_dispatcher.dart [hunk 3]
```diff
@@ -158,19 +158,27 @@ class IsolateDispatcher {
...
+    var channel = IsolateChannel<Uint8List>.connectReceive(receivePort);
+    channel.stream.listen(
+        (message) {
+          // The first byte of messages from isolates indicates whether the
+          // entire compilation is finished. Sending this as part of the message
+          // buffer rather than a separate message avoids a race condition where
+          // the host might send a new compilation request with the same ID as
+          // one that just finished before the [IsolateDispatcher] receives word
+          // that the isolate with that ID is done. See sass/dart-sass#2004.
+          _channel.sink.add(Uint8List.sublistView(message, 1));
```
Comment (ntkme) [inline lib/src/embedded/isolate_dispatcher.dart:170]: To be extra safe, this should come after the if branch below. In other words, after isolate is deactivated / resource is released.

**Review by ntkme — CHANGES_REQUESTED** [review]

File: lib/src/embedded/isolate_dispatcher.dart (hunk 3 above)
Comment (nex3) [reply lib/src/embedded/isolate_dispatcher.dart:170]: This has to come _before_ `_channel.sink.close()`, or the call to `add()` will fail. I think it's safe enough to rely on Dart's single-threading guarantees here.
