### PR TITLE
Fix a selector parsing bug in indented syntax

### LINKED ISSUE #1002: Wrong parsing of valid SASS syntax
When I try to parse the following SASS file I get a strange warning
```
WARNING on line 1, column 1 of normalize.sass:
This selector doesn't have any properties and won't be rendered.
1 │ ┌ button,
2 │ └ input, /* 1 */
```
However, if I remove the comment from line 2 - the warning goes away.
Also, if I move the comma after the comment - the warning goes away.
If just does not make sense to me.
```sass
button,
input, /* 1 */
select /* 2, 3 */
  overflow: visible
  text-transform: none
```

### PR DESCRIPTION
**Pull request by jathak**
Fixes #1002.

In the indented syntax, a selector list may continue onto another line if the previous line ends with a comma. Previously, if there was a comment after the comma, it wouldn't be recognized and the selector would be broken in two (with the first selector having no properties).

This fixes the parser to ignore comments when looking for the comma at the end of a line.

See sass/sass-spec#1532.

### CODE REVIEW

File: lib/src/parse/sass.dart [hunk 1]
```diff
@@ -48,12 +48,23 @@ class SassParser extends StylesheetParser {
...
       buffer.writeCharCode($lf);
-    } while (buffer.trailingString.trimRight().endsWith(",") &&
-        scanCharIf(isNewline));
+    } while (_endsWithComma(buffer.trailingString) && scanCharIf(isNewline));
 
     return buffer.interpolation(scanner.spanFrom(start));
   }
 
+  // Returns true if [text] ends with a comma, ignoring whitespace and comments.
+  bool _endsWithComma(String text) {
```
Comment (nex3) [inline lib/src/parse/sass.dart:57]: I'm concerned that this doesn't respect CSS tokenization rules. For example, if `"//"` somehow made it into the selector, it would be considered a comment here rather than a string. Since `almostAnyValue()` does fully tokenize, maybe we can get it to be a little more clever here. Maybe add an `omitComments` parameter that tells it not to include comments in the buffer?

Comment (jathak) [reply lib/src/parse/sass.dart:57]: Yeah, that makes sense. Originally, I didn't think that would work, since the comments would be omitted in the output, but since even loud comments are omitted within selectors, it should be fine.

Comment (jathak) [reply lib/src/parse/sass.dart]: Done

**Comment by nex3** [comment]
Don't forget to add a CHANGELOG entry for this!

**Comment by jathak** [comment]
Do you know what's going on with Appveyor here?

**Comment by nex3** [comment]
Looks like possibly a flake? I'll try restarting it.
