### PR TITLE
Fix source span for calculation deprecation warnings

### LINKED ISSUE #2081: 1.67.0 reports wrong source span for abs-percent deprecation warning
Followings are the deprecation warning output of compiling twbs/bootstrap. Dart Sass 1.67.0 appears to have incorrect source span for the abs-percent deprecation warning.

With sass 1.66.1:

```
Deprecation Warning: Passing percentage units to the global abs() function is deprecated.
In the future, this will emit a CSS abs() function to be resolved by the browser.
To preserve current behavior: math.abs(100%)
To emit a CSS abs() now: abs(#{100%})
More info: https://sass-lang.com/d/abs-percent

   ╷
57 │   $dividend: abs($dividend);
   │              ^^^^^^^^^^^^^^
   ╵
    scss/vendor/_rfs.scss 57:14         divide()
    scss/mixins/_grid.scss 59:12        row-cols()
    scss/mixins/_grid.scss 85:13        @content
    scss/mixins/_breakpoints.scss 68:5  media-breakpoint-up()
    scss/mixins/_grid.scss 72:5         make-grid-columns()
    scss/_grid.scss 38:3                @import
    scss/bootstrap.scss 20:9            root stylesheet

```

---

With sass 1.67.0:

```
Deprecation Warning: Passing percentage units to the global abs() function is deprecated.
In the future, this will emit a CSS abs() function to be resolved by the browser.
To preserve current behavior: math.abs(100%)
To emit a CSS abs() now: abs(#{100%})
More info: https://sass-lang.com/d/abs-percent

   ╷
1  │ ┌ @import "mixins/banner";
2  │ │ @include bsBanner("");
3  │ │ 
4  │ │ 
5  │ │ // scss-docs-start import-stack
6  │ │ // Configuration
7  │ │ @import "functions";
8  │ │ @import "variables";
9  │ │ @import "variables-dark";
10 │ │ @import "maps";
11 │ │ @import "mixins";
12 │ │ @import "utilities";
13 │ │ 
14 │ │ // Layout & components
15 │ │ @import "root";
16 │ │ @import "reboot";
17 │ │ @import "type";
18 │ │ @import "images";
19 │ │ @import "containers";
20 │ │ @import "grid";
21 │ │ @import "tables";
22 │ │ @import "forms";
23 │ │ @import "buttons";
24 │ │ @import "transitions";
25 │ │ @import "dropdown";
26 │ │ @import "button-group";
27 │ │ @import "nav";
28 │ │ @import "navbar";
29 │ │ @import "card";
30 │ │ @import "accordion";
31 │ │ @import "breadcrumb";
32 │ │ @import "pagination";
33 │ │ @import "badge";
34 │ │ @import "alert";
35 │ │ @import "progress";
36 │ │ @import "list-group";
37 │ │ @import "close";
38 │ │ @import "toasts";
39 │ │ @import "modal";
40 │ │ @import "tooltip";
41 │ │ @import "popover";
42 │ │ @import "carousel";
43 │ │ @import "spinners";
44 │ │ @import "offcanvas";
45 │ │ @import "placeholders";
46 │ │ 
47 │ │ // Helpers
48 │ │ @import "helpers";
49 │ │ 
50 │ │ // Utilities
51 │ │ @import "utilities/api";
52 │ └ // scss-docs-end import-stack
   ╵
    scss/bootstrap.scss 1:1             divide()
    scss/mixins/_grid.scss 59:12        row-cols()
    scss/mixins/_grid.scss 85:13        @content
    scss/mixins/_breakpoints.scss 68:5  media-breakpoint-up()
    scss/mixins/_grid.scss 72:5         make-grid-columns()
    scss/_grid.scss 38:3                @import
    scss/bootstrap.scss 20:9            root stylesheet

```

### PR DESCRIPTION
**Pull request by ntkme**
https://github.com/sass/sass-spec/pull/1937

- Closes #2081

### CODE REVIEW

File: lib/src/visitor/async_evaluate.dart [hunk 1]
```diff
@@ -2472,6 +2476,9 @@ final class _EvaluateVisitor
       }
       throwWithTrace(_exception(error.message, node.span), error, stackTrace);
     }
+    _callableNode = oldCallableNode;
```
Comment (nex3) [inline lib/src/visitor/async_evaluate.dart:2479]: If you put this in a `finally` clause on the `try`, you can avoid needing to create the intermediate `result` variable.

Comment (ntkme) [reply lib/src/visitor/async_evaluate.dart]: I thought if we're going to throw there is no need to set the variable back to original value, but styling wise finally block looks better.

Comment (nex3) [reply lib/src/visitor/async_evaluate.dart]: `finally` gets run even if nothing throws, so it's useful for cases like these where you want to do something _after_ a return.

**Review by nex3 — APPROVED** [review]
