### PR TITLE
Fix custom property parsing in plain CSS

### LINKED ISSUE #1104: webpack builds using sass-loader are failing on updating to sass@1.26.12
The fix committed in #1096 is causing the webpack builds using sass-loader to fail with the following error:
```
ERROR in ./web/src/shared/themes/bootstrap/bootstrap.scss (./node_modules/css-loader/dist/cjs.js??ref--11-1!./node_modules/sass-loader/dist/cjs.js??ref--11-2!./web/src/shared/themes/bootstrap/bootstrap.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
TypeError: Instance of 'SassColor0': type 'SassColor0' is not a subtype of type 'SassString0'
 @ ./web/src/shared/themes/bootstrap/bootstrap.scss 4:14-168
```

The bootstrap.scss has the following code:
```scss
@import '~bootstrap-vue/dist/bootstrap-vue';
@import '~bootstrap/dist/css/bootstrap';
@import '../../css/bootstrap-overrides';
@import "../globals/globals";
```

On reverting to sass@1.26.11 the webpack build is working fine.

Any insights on what could be the issue here would be of great help. Thanks :)

### PR DESCRIPTION
**Pull request by nex3**
Closes #1104
See sass/sass-spec#1575

### CODE REVIEW

File: lib/src/parse/stylesheet.dart [hunk 1]
```diff
@@ -503,8 +503,11 @@ abstract class StylesheetParser extends Parser {
   /// This is only used in contexts where declarations are allowed but style
   /// rules are not, such as nested declarations. Otherwise,
   /// [_declarationOrStyleRule] is used instead.
-  @protected
```
Comment (Awjin) [inline lib/src/parse/stylesheet.dart:506]: Does this no longer apply?

**Review by Awjin — APPROVED** [review]

File: lib/src/parse/stylesheet.dart (hunk 1 above)
Comment (nex3) [reply lib/src/parse/stylesheet.dart:506]: I'm not sure why it was there in the first place—the method is private, so it can't be referenced from subclasses anyway (unless those subclasses are in the same file which they aren't).
